### ISSUE TITLE
java.lang.ClassNotFoundException: cats.Cartesian

### ISSUE THREAD

**Issue by lxohi** [pavlosgi/freecli#2]
I'm using freecli with circe-0.10.1
This version of circe requires cats-1.4.0 while freecli requires cats-0.8.1

**cats.Cartesian** has been renamed to **Semigroupal** since cats-1.0.0
Now [there](https://github.com/typelevel/cats/blob/774fb51d1365e1adef7fa71f09b1410941264f60/core/src/main/scala/cats/package.scala#L114) was only a type alias called Cartesian.

Here is the problem:

- If I use cats-0.8.1, there will be some newer classes in cats missing and could not even compile when using circe.
- If I use cats-1.4.0, compile was totally fine but will raise a ClassNotFoundException when running freecli DSLs.

Is it re-compile freecli with higher version of cats be a solution here?

**Comment by pavlosgi** [comment]
I will look into this and get back to you

**Comment by pavlosgi** [comment]
I updated cats version to 1.5 and released 0.1.4, should be updated in Maven soon

**Comment by lxohi** [comment]
It works perfectly now! Thank you so much for the release!

**Comment by pavlosgi** [comment]
No problem!
